### ISSUE TITLE
add gfortran debug stage to firebot to catch unused variables

### ISSUE THREAD

**Issue by gforney** [firemodels/bot#129]
Despite using -warn unused in the _db compile flags, Intel does not catch these unused variables if they are within a subroutine that is "CONTAINED" within another.

But, gfortran does catch these.  Add a gfortran _db compile stage to firebot and report any unused warnings.

**Comment by rmcdermo** [comment]
Yep.  I see it.

**Comment by gforney** [comment]
implemented now in both firebot and smokebot
