### ISSUE TITLE
Make tags consistent across repos for bundles

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/bot#806]
Still looks like there is a bug in the bot.  It's still reporting 2 SMV repos, one that is ahead by 77 commits.  Also, I think that in the long run we should apply analogous tags to all the repos.  For example, OUT-6.9.0-0..., FIG-6.9.0-0..., etc.  Last, it looks like you tried to do this with EXP, but omitted the dots in the tag name.  Does not need to be fixed for this release, but just something we should put on the to-do list.  Let me know if you want me to post an Issue.

**Comment by gforney** [comment]
going through old issues - should be fixed . reopen if you still see a problem that I missed
